name: Run Python Bot Every 2 Hours

on:
  schedule:
    # Se ejecuta cada 2 horas entre 8:00 AM y 8:00 PM hora de Venezuela (UTC-4)
    - cron: "0 12-23/2 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Configura el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Ajusta según la versión que uses

      # Instala dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Configura las variables de entorno
      - name: Export environment variables
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_VERSION: ${{ secrets.API_VERSION }}
          X_USERNAME: ${{ secrets.X_USERNAME }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          NEWS_API_URL: ${{ secrets.NEWS_API_URL }}
          NEWS_API_VERSION: ${{ secrets.NEWS_API_VERSION }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: echo "Environment variables loaded"

      # Ejecuta el script
      - name: Run Python bot
        run: python main.py
